name: Build

on:
  workflow_dispatch:
    inputs:
      formula:
        required: true
        type: string
  workflow_call:
    inputs:
      formula:
        required: true
        type: string

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            arch:
          - runner: ubuntu-22.04-arm
            arch:
          - runner: macos-14
            arch: x86_64
          - runner: macos-14
            arch: arm64
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main

      - name: Get version for setup-ruby
        run: |
          SETUP_RUBY_VERSION=${{ inputs.formula }}
          SETUP_RUBY_VERSION=${SETUP_RUBY_VERSION//rv-ruby}
          SETUP_RUBY_VERSION=${SETUP_RUBY_VERSION//@}
          if [[ "$SETUP_RUBY_VERSION" == "3.2."* ]]; then
            echo SETUP_RUBY_VERSION=${SETUP_RUBY_VERSION} >> $GITHUB_ENV
          fi

      # Static gem extensions typically require the same Ruby version available already
      - uses: ruby/setup-ruby@v1
        id: setup-ruby
        if: ${{ env.SETUP_RUBY_VERSION != '' }}
        with:
          ruby-version: ${{ env.SETUP_RUBY_VERSION }}

      - name: Install Homebrew
        run: |
          if [[ -n "${{ matrix.arch }}" ]]; then
            arch -${{ matrix.arch }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          if [[ -d /home/linuxbrew ]]; then
            echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
            echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          fi

      - name: Tap repo
        run: bin/setup

      - name: Build rv Ruby
        run: |
          if [[ -n "${{ steps.setup-ruby.outputs.ruby-prefix }}" ]]; then
            export HOMEBREW_BASERUBY="${{ steps.setup-ruby.outputs.ruby-prefix }}/bin/ruby"
          fi
          mkdir -p rubies/
          cd rubies
          if [[ -n "${{ matrix.arch }}" ]]; then
            arch -${{ matrix.arch }} brew rv-package --verbose ${{ inputs.formula }}
          else
            brew rv-package --verbose ${{ inputs.formula }}
          fi

      - name: Upload rv Ruby
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ inputs.formula }}_${{ matrix.runner }}
          path: ${{ github.workspace }}/rubies

      - name: Test Portable Ruby
        run: |
          mkdir -p rv-ruby/
          tar --strip-components 2 -C rv-ruby -xf rubies/*.tar.gz
          export PATH="${PWD}/rv-ruby/bin:${PATH}"
          if [[ "${{ inputs.formula }}" == "rv-ruby@0.49" ]]; then
            ruby --version
          else
            ruby --version --yjit
            ruby -r debug -r bigdecimal -r json -r yaml -r reline -e "true"
          fi
