name: Build

on:
  workflow_dispatch:
    inputs:
      formula:
        required: true
        type: string
  workflow_call:
    inputs:
      formula:
        required: true
        type: string

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-15-intel # intel
          - macos-14 # arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main

      - name: Get version for setup-ruby
        run: |
          VERSION=${{ inputs.formula }}
          VERSION=${VERSION//jdx-ruby}
          VERSION=${VERSION//@}
          echo VERSION=${VERSION} >> $GITHUB_ENV

      # Static gem extensions typically require the same Ruby version available already
      - uses: ruby/setup-ruby@v1
        id: setup-ruby
        if: ${{ inputs.formula != 'jdx-ruby@0.49' && inputs.formula != 'jdx-ruby-dev' }}
        with:
          ruby-version: ${{ env.VERSION }}

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Tap repo
        run: bin/setup

      - name: Build jdx Ruby
        run: |
          if [[ -n "${{ steps.setup-ruby.outputs.ruby-prefix }}" ]]; then
            export HOMEBREW_BASERUBY="${{ steps.setup-ruby.outputs.ruby-prefix }}/bin/ruby"
          fi
          mkdir -p rubies/
          cd rubies
          brew jdx-package --verbose ${{ inputs.formula }}

      - name: Upload jdx Ruby
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ inputs.formula }}_${{ matrix.runner }}
          path: ${{ github.workspace }}/rubies

      - name: Test Portable Ruby
        run: |
          mkdir -p jdx-ruby/
          tar --strip-components 2 -C jdx-ruby -xf rubies/*.tar.gz
          export PATH="${PWD}/jdx-ruby/bin:${PATH}"
          if [[ "${{ inputs.formula }}" == "jdx-ruby@0.49" ]]; then
            ruby --version
          else
            ruby --version --yjit
            ruby -r debug -r bigdecimal -r json -r yaml -r reline -e "true"
          fi
